language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec rspec spec
before_install:
  - yes | gem update --system --force
  - gem install bundler:1.17.3
before_script:
  - cp config/database_example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - psql -c 'create database buzz_test' -U postgres
  - psql -c 'create role root superuser createdb createrole inherit login replication' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
cache:
  bundler: true
addons:
  postgresql: "9.4"
services:
  - postgresql
