pg_settings: &pg_settings
  adapter: postgresql
  encoding: utf8
  reconnect: true
  pool: 5

from_env: &from_env
  <<: *pg_settings
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host:     <%= ENV["DB_HOSTNAME"] %>
  database: <%= ENV["DB_NAME"] %>
  port:     <%= ENV["DB_PORT"] %>

development:
  <<: *from_env

pre_production:
  <<: *from_env

production:
  <<: *from_env
